language: objective-c
sudo: false
xcode_workspace: Gureum.xcworkspace
osx_image: xcode11
install:
  - gem update cocoapods
  - pod install --repo-update
  - brew update && brew install shellcheck swiftformat
matrix:
  include:
    - osx_image: xcode11
      xcode_sdk: macosx
      xcode_scheme: OSX
      xcode_destination: platform=macOS
    #- osx_image: xcode9.4
    # xcode_sdk: iphonesimulator
    # xcode_scheme: App
    # xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
script:
  - shellcheck tools/*.sh
  - swiftformat --lint OSXCore/ OSX/ GureumTests/ Preferences/ OSXTestApp/
  - set -o pipefail && xcodebuild -workspace Gureum.xcworkspace -scheme OSX -sdk macosx -destination platform\=macOS build test | xcpretty
