language: objective-c
sudo: false
xcode_workspace: Gureum.xcworkspace
osx_image: xcode9.4
install:
  - gem install cocoapods --pre
  - pod install --repo-update
matrix:
  include:
    - osx_image: xcode10
      xcode_sdk: macosx
      xcode_scheme: OSX
      xcode_destination: platform=macOS
    #- osx_image: xcode9.4
    # xcode_sdk: iphonesimulator
    # xcode_scheme: App
    # xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
